// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgzmdsjuywsvphulhxre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indnem1kc2p1eXdzdnBodWxoeHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODA2ODcsImV4cCI6MjA2NDI1NjY4N30.CocRnhHzLciv5CBIMznYNOgOzgfUT9wlbMrfWr1g-u4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);